# Use hadolint to test all Dockerfiles in this repository
lint dockerfile:
  image: hadolint/hadolint:latest-debian
  stage: test
  script:
    - for Dockerfile in $(find . -type f -name 'Dockerfile' 2>/dev/null); do hadolint $Dockerfile; done