stages:
  - test

variables:
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

# Use hadolint to test all Dockerfiles in this repository
lint dockerfile:
  image: hadolint/hadolint:latest-debian
  stage: test
  script:
    - hadolint ./saltmaster/Dockerfile
    - hadolint ./saltminion/Dockerfile