version: '3.3'

services:
  saltmaster:
    build: saltmaster
    image: saltmaster
    expose:
      - "4505"
      - "4506"
    volumes:
      - ./saltmaster/srv/pillar:/srv/pillar
      - ./saltmaster/srv/salt:/srv/salt

  minion01:
    build: saltminion
    image: saltminion
    restart: always
    depends_on:
      - saltmaster

  minion02:
    build: saltminion
    image: saltminion
    restart: always
    depends_on:
      - saltmaster
